from django.db import models
from django.conf import settings


class TimeMixin(models.Model):
  time_created = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
  time_modified = models.DateTimeField(auto_now=True, blank=True)

  class Meta:
    abstract = True


class OwnedMixin(models.Model):
  user = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE
  )

  class Meta:
    abstract = True


class DeletedFlag:
  time_deleted = models.DateTimeField()


class SourceType(models.TextChoices):
  USER_GENERATED = 'ug', 'User Generated / User Submitted'
  USER_INTERACTION = 'ui', 'Implicit Feedback from User Interaction (inferred from user actions)'
  MODEL_OUTPUT = 'ml', 'Machine Learning Model Output / Predictions'
  EXTRACTED = 'ex', 'Extracted from another source (open dataset, web crawl, etc)',
  WEAK_SUPERVISION = 'ws', 'Weak Supervision (generated by a heuristic / weak labeling function)'
  UNKNOWN = '', 'Unknown'


class SourceMixin(models.Model):
  source_id = models.CharField(max_length=128, blank=True, default='')

  SourceType = SourceType
  source_type = models.CharField(
    max_length=2,
    choices=SourceType.choices,
    blank=True,
    default=''
  )

  class Meta:
    abstract = True


# class VerificationStatus(models.Choices):
#   CORRECT = True, 'Verified Correct'
#   INCORECT = False, 'Verified Incorrect'
#   __empty__ = 'Not Verified'  # == None


class VerificationMixin(models.Model):
  # VerificationStatus = VerificationStatus
  verification_status = models.NullBooleanField(
    blank=True,
    default=None,
    choices=(
      (True, 'Verified Correct'),
      (False, 'Verified Incorrect'),
      (None, 'Not Verified'),
    )
  )
  time_verified = models.DateTimeField(null=True, blank=True, default=None)

  class Meta:
    abstract = True