version: '3.6'

services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: cleanser
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
#  django:
#    ports:
#      - "8000:8000"
#      depends_on:
#        - db
#        - redis
#  celery:
#    build: .
#    command: celery -A proj worker -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - redis
#  redis:
#    image: "redis:alpine"